'''
From projecteuler.net 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def sumEvenFibonacci(n):
    return sum([fibonacci(i) for i in range(1, n+1) if fibonacci(i) % 2 == 0])
  

#This is a non optimized solution because of the recursive fibonacci
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
  
